-- Expand MatchStage enum to persist explicit knockout rounds.
ALTER TYPE "MatchStage" ADD VALUE IF NOT EXISTS 'ROUND_OF_32';
ALTER TYPE "MatchStage" ADD VALUE IF NOT EXISTS 'ROUND_OF_16';
ALTER TYPE "MatchStage" ADD VALUE IF NOT EXISTS 'QUARTER_FINAL';
ALTER TYPE "MatchStage" ADD VALUE IF NOT EXISTS 'SEMI_FINAL';
ALTER TYPE "MatchStage" ADD VALUE IF NOT EXISTS 'THIRD_PLACE';
